### ISSUE TITLE
Question about INTERACTION leaderboard

### ISSUE THREAD

**Issue by kkk00714** [OpenDriveLab/HDGT#12]
@jiaxiaosong1002 Hello, I would like to know if the data for HDGT on the INTERACTION leaderboard single-agent track is based on ’all‘ types of scenarios or only on ’regular‘ types. Up to the end of 2023, all methods only included data for ’all‘ types. However, I found that when I only submit ’regular‘ data, it still generates data for ’all‘ types.

**Comment by jiaxiaosong1002** [comment]
@woyoudian2gou   Yes, it is based on "all".  Since "regular" and "gen" are both subset of "all", there is no need to submit to the sub-type.

For your information, I have not participated in the dataset curation **since 2021** and not affilated with MSC Lab as well. Thus, **there might be changes happend** and I suggest you directly contacting them for accurate information.
